ERROR:tornado.application:Future <tornado.concurrent.Future object at 0x7f6bd6c26e48> exception was never retrieved: Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/tornado/gen.py", line 1021, in run
    yielded = self.gen.throw(*exc_info)
  File "client.py", line 22, in fetch
    response = yield http_client.fetch(request)
  File "/usr/local/lib/python3.5/site-packages/tornado/gen.py", line 1015, in run
    value = future.result()
  File "/usr/local/lib/python3.5/site-packages/tornado/concurrent.py", line 237, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 3, in raise_exc_info
tornado.curl_httpclient.CurlError: HTTP 599: transfer closed with 12868254 bytes remaining to read
downloaded 16233 total is now  16233
downloaded 2199 total is now  18432
downloaded 16384 total is now  34816
downloaded 16384 total is now  51200
downloaded 16384 total is now  67584
downloaded 16384 total is now  83968
downloaded 3072 total is now  87040
downloaded 1024 total is now  88064
downloaded 1024 total is now  89088
downloaded 16384 total is now  105472
downloaded 16384 total is now  121856
downloaded 16384 total is now  138240
downloaded 16384 total is now  154624
downloaded 2048 total is now  156672
downloaded 1024 total is now  157696
downloaded 1024 total is now  158720
downloaded 3072 total is now  161792
Traceback (most recent call last):
  File "client.py", line 30, in <module>
    tornado.ioloop.IOLoop.instance().start()
  File "/usr/local/lib/python3.5/site-packages/tornado/ioloop.py", line 862, in start
    event_pairs = self._impl.poll(poll_timeout)
KeyboardInterrupt
